runtime: python
env: flex
entrypoint: gunicorn -b :$PORT main:app

runtime_config:
operating_system: ubuntu22

handlers:
- url: /static
  static_dir: static
- url: /.*
  script: auto

manual_scaling:
  instances: 1
resources:
  cpu: 1
  memory_gb: 2
  disk_size_gb: 10